include: ./flutter_samples_analysis_options.yaml

analyzer:
  exclude:
    - lib/models/models.g.dart
    - 'lib/**/**.freezed.dart'
    - 'lib/**/**.g.dart'
    - 'docs/**.dart'
  errors:
    missing_required_param: warning
    missing_return: warning
linter:
  rules:
    - always_put_control_body_on_new_line
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    # - avoid_dynamic_calls #experimental, not available
    - avoid_field_initializers_in_const_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_js_rounded_ints
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_renaming_method_parameters
    - avoid_returning_null
    # Not work as documented: https://dart-lang.github.io/linter/lints/avoid_returning_null_for_future.html
    # - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_unused_constructor_parameters
    # - cascade_invocations
    - cast_nullable_to_non_nullable #experimental
    - comment_references
    - directives_ordering
    # - do_not_use_environment
    - exhaustive_cases
    - file_names
    - flutter_style_todos
    - iterable_contains_unrelated_type
    - join_return_with_assignment
    # - lines_longer_than_80_chars
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_default_cases #experimental
    - null_check_on_nullable_type_parameter #experimental
    - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_initializing_formals
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - sized_box_for_whitespace
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks #experimental
    - unnecessary_nullable_for_final_variable_declarations #experimental
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_this
    - use_function_type_syntax_for_parameters
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables #experimental
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - void_checks
