name: ks_flutter_commons
description: My Flutter common source codes.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  cloud_firestore: ^3.1.6
  cloud_functions: ^3.2.5
  connectivity_plus: ^2.2.0
  firebase_analytics: ^9.0.5
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_storage: ^10.2.4
  flutter:
    sdk: flutter
  intl: ^0.17.0
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
