name: ks_flutter_commons
description: My Flutter common source codes.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  cloud_firestore: ^4.4.3
  cloud_functions: ^4.0.11
  connectivity_plus: ^3.0.3
  firebase_analytics: ^10.1.4
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  intl: ^0.17.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
